In [2]:
import numpy as np
from numpy import random as rand

In [4]:
idx=np.arange(18)
rand.shuffle(idx)

distrb=np.array([11,11,12,12,12]) 
A=None
a=[1,2,3,4,5,6,7,8,9,10]
a[0:6]

[1, 2, 3, 4, 5, 6]

In [10]:

def Num2Res(mode=None):
    
    Num_Values=np.hstack([5*np.ones(4,dtype=int),4*np.ones(4,dtype=int),3*np.ones(4,dtype=int),2*np.ones(4,dtype=int),np.ones(2,dtype=int)])    
    Num_Tokens=np.array([6,6,8,8,5,5,9,9,4,4,10,10,3,3,11,11,2,12],dtype=int)
    
    if mode==1:
        distrb=np.array([11,11,12,12,12]) 
    elif mode==2:  
        distrb=np.array([11,11,11,11,14]) 
    else:
        distrb=np.array([10,12,12,12,12]) 
    rand.shuffle(distrb)
    
    Nam=['Brick','Ore','Lumber','Grain','Sheep']
    idx=np.arange(18)
    
    d=None
    while d != distrb[3]:
        c=None
        while c != distrb[2]:
            b=None
            while b != distrb[1]:
                a=None
                while a != distrb[0]:
                    rand.shuffle(idx)
                    Num_Values=Num_Values[idx]
                    Num_Tokens=Num_Tokens[idx]
                    a=int(sum(Num_Values[:3]))
                b=int(sum(Num_Values[3:6]))
            c=int(sum(Num_Values[6:10]))
        d=int(sum(Num_Values[10:14]))
    
    Res=list(np.zeros(19))
    for i in np.arange(18):
        if i <=2:
            Res[i]=np.array([Nam[0],Num_Tokens[i]])
        elif 2 < i and i <= 5:
            Res[i]=np.array([Nam[1],Num_Tokens[i]])
        elif 5 < i and i <= 9:
            Res[i]=np.array([Nam[2],Num_Tokens[i]])
        elif 9 < i and i <= 13:
            Res[i]=np.array([Nam[3],Num_Tokens[i]])
        else:
            Res[i]=np.array([Nam[4],Num_Tokens[i]])
    Res[-1]=np.array(['Desert',0])
    Num_Values=np.append(Num_Values,0)
    return(Res,Num_Values)
        

In [27]:
def pickn(box=None,idx=None,result=None): #list, array, list
    n=0
    change=box
    for k in idx:
        result.append(k)
        
    for i in np.sort(idx):
        change=np.append(change[:i-n],change[i+1-n:])
        n=n+1
        
    return(box,list(change),result) #list, list, list

def pick1(box=None,idx=None,result=None): #list, array, list
    change=box
    result.append(idx)
    change=np.append(change[:idx],change[idx+1:])
        
    return(box,list(change),result) #list, list, list

def checkall(check=None,require=None):
    urn=np.arange(len(check))
    for i in urn:
        if check[i] in require:
            urn[i]=1
        else:
            urn[i]=0
    return(all(urn))

def disk_sum(number=None,radius=None): #radius >= 1    
    if (len(number)-1) % 6:
        return("Not a complete ring")
    else:        
        sumset=np.ones(6*(radius**2), dtype=int)
        for i in np.arange(6):
            re=np.arange(1,7)                
            sumset[i]=int(number[0]+number[i+1]+number[re[np.mod(i+1,6)]])
                
        for x in np.arange(2,radius+1):
            n=6*(x)**2-6*(x-1)**2
            for k in np.arange(6):
                
                idd=k*(x+1)+6*(x-1)**2
                even=(x**3)-((x-1)**3) + k*x
                odd= ((x-1)**3)-((x-2)**3) + k*(x-1)
                
                hexseq=np.ones(int(n/6)+2,dtype=int)
                for m in np.arange(int(n/6)+2):
                    if not m % 2:
                        hexseq[m]=int(even+m/2)
                    else:
                        hexseq[m]=int(odd+m//2)
                if k==5:
                    hexseq[-1]=hexseq[-2]
                    hexseq[-2]=int(((x-1)**3)-((x-2)**3))
                for l in np.arange(len(hexseq[:-2])):
                    sumset[int(idd+l)]=int(number[hexseq[l]]+number[hexseq[l+1]]+number[hexseq[l+2]])    
    return(sumset)
                
                


def setupboard(hexes=None):
    Token=list(hexes[1])
    
    sumrange=[9,10,11]
    for a in np.arange(len(Token)): #looping over all hex as starting hex
        order=[]
        bin_=pick1(available,a,order)[1]
        order=pick1(available1,a,order)[2]
        ids=np.arange(len(bin_))
        rand.shuffle(ids)
        first_ring=np.append(order,bin_[ids[:6]])
        
        break
    return(order)
            


        
        

In [28]:
C=[1]
B=np.arange(19)
test=Num2Res(3)
number=test[1]
while not checkall(C,[9,10,11]):
    rand.shuffle(B)
    #while list(number[B]).index(0)  < 6:
        #rand.shuffle(B)
    C=disk_sum(number[B],1)

x=2
n=6*(x)**2-6*(x-1)**2

print(number[B],B,C)

[5 2 3 3 3 2 2 5 4 1 4 5 5 2 4 1 4 0 3] [ 8  6  3 17 13  9 10  0 11 16 15  5  2  1 14 12  4 18  7] [10 11 11 10  9  9]


In [29]:
disk_sum(number[B],2)

array([10, 11, 11, 10,  9,  9, 11,  9,  8,  8, 10, 12, 13, 11, 10,  9,  9,
        7,  7,  8,  6,  5,  7, 10])

In [30]:
i=0
sumset=[0]
lhalf=B[7:]
while not checkall(sumset,[8,9,10,11]):
    rand.shuffle(lhalf)
    B[7:]=lhalf
    A=number[B]
    sumset=[]
    for k in np.arange(6):
        hexseq=np.ones(int(n/6)+2,dtype=int)
        for m in np.arange(int(n/6)+2):
            if not m % 2:
                hexseq[m]=int((x**3)-((x-1)**3)+m/2+k*x)
            else:
                hexseq[m]=int(((x-1)**3)-((x-2)**3)+m//2+k*(x-1))
        if k==5:
            hexseq[-1]=hexseq[-2]
            hexseq[-2]=int(((x-1)**3)-((x-2)**3))
        for l in np.arange(len(hexseq[:-2])):
            sumset=np.append(sumset,int(A[hexseq[l]]+A[hexseq[l+1]]+A[hexseq[l+2]]))
    i=i+1



In [32]:
print(number[B],sumset)

[5 2 3 3 3 2 2 2 5 0 5 1 4 1 4 5 4 3 4] [  9.  10.   8.   8.  11.   9.   8.  10.   8.   8.   9.  11.  11.   8.   9.
   9.   8.   8.]


In [31]:
print(disk_sum(number[B],2),i)


[10 11 11 10  9  9  9 10  8  8 11  9  8 10  8  8  9 11 11  8  9  9  8  8] 5671


In [112]:
A=[1,2,3,4,5]
B=[1,2,3,4]
C=[2,3,4,5,6,7]
for l in np.arange(len(A[:-2])):
    B=np.append(B,int(C[A[l]]+C[A[l+1]]+C[A[l+2]]))

B

array([ 1,  2,  3,  4, 12, 15, 18])

In [134]:
n=18
x=2
sumset=[]
number=test[1]
for k in np.arange(6):
        hexseq=np.zeros(int(n/6)+2,dtype=int)
        for m in np.arange(int(n/6)+2):
            if not m % 2:
                hexseq[m]=int((x**3)-((x-1)**3)+m/2+k*x)
            else:
                hexseq[m]=int(((x-1)**3)-((x-2)**3)+m//2+k*(x-1))
        if k==5:
            hexseq[-1]=hexseq[-2]
            hexseq[-2]=int(((x-1)**3)-((x-2)**3))
        for l in np.arange(len(hexseq[:-2])):
            sumset=np.append(sumset,int(number[hexseq[l]]+number[hexseq[l+1]]+number[hexseq[l+2]]))
sumset.astype(int)


array([ 11.,  13.,  11.,   8.,   7.,   6.,   8.,  10.,  12.,  14.,  14.,
        10.,   8.,  12.,  10.,   7.,  10.,   7.])

In [181]:
np.ones(int(n/6)+2, dtype=int)
ids=rand.randint(0,17)
ids

6

In [268]:
a=[[0,1,-1],[-1,1,0],[-1,0,1],[0,-1,1],[1,-1,0],[1,0,-1]]
a.append([[0,0,0],[1,2,3]])
print(a)

[[0, 1, -1], [-1, 1, 0], [-1, 0, 1], [0, -1, 1], [1, -1, 0], [1, 0, -1], [[0, 0, 0], [1, 2, 3]]]


In [9]:
ids=np.arange(18)
rand.shuffle(ids)
ids

array([13,  7,  2, 15,  5,  6, 10,  4, 11, 14, 17,  8,  0, 16,  9,  3,  1,
       12])

In [273]:
def spiral(center=None,radius=None):
    cubedirect=np.vstack([np.array([1,-1,0]),np.array([1,0,-1]),np.array([0,1,-1]),np.array([-1,1,0]),np.array([-1,0,1]),np.array([0,-1,1])])       

    result=[np.array(center)]
    
    for k in np.arange(1,radius+1):
        cube=np.array(center)+cubedirect[-2]*k
        result.append(cube)
        for i in np.arange(6):
            for j in np.arange(k):
                cube = cube + cubedirect[i]
                result.append(cube)
        result=result[:-1]

    return result
