In [368]:
import numpy as np
from numpy import random as rand

In [15]:
Num_Tokens=np.hstack([5*np.ones(4,dtype=int),4*np.ones(4,dtype=int),3*np.ones(4,dtype=int),2*np.ones(4,dtype=int),np.ones(2,dtype=int)])    
Num_Tokens=np.vstack([np.array([6,6,8,8,5,5,9,9,4,4,10,10,3,3,11,11,2,12]),Num_Tokens])

print(Num_Tokens)


[[ 6  6  8  8  5  5  9  9  4  4 10 10  3  3 11 11  2 12]
 [ 5  5  5  5  4  4  4  4  3  3  3  3  2  2  2  2  1  1]]


In [108]:
idx=np.arange(18)
rand.shuffle(idx)

distrb=np.array([11,11,12,12,12]) 
A=None
a=[1,2,3,4,5,6,7,8,9,10]
a[0:6]

[1, 2, 3, 4, 5, 6]

In [394]:

def Num2Res(mode=None):
    
    Num_Values=np.hstack([5*np.ones(4,dtype=int),4*np.ones(4,dtype=int),3*np.ones(4,dtype=int),2*np.ones(4,dtype=int),np.ones(2,dtype=int)])    
    Num_Tokens=np.array([6,6,8,8,5,5,9,9,4,4,10,10,3,3,11,11,2,12],dtype=int)
    
    distrb=0
    if mode==1:
        distrb=np.array([11,11,12,12,12]) 
    elif mode==2:  
        distrb=np.array([11,11,11,11,14]) 
    else:
        distrb=np.array([10,12,12,12,12]) 
    rand.shuffle(distrb)
    
    Nam=['Brick','Ore','Lumber','Grain','Sheep']
    idx=np.arange(18)
    
    d=None
    while d != distrb[3]:
        c=None
        while c != distrb[2]:
            b=None
            while b != distrb[1]:
                a=None
                while a != distrb[0]:
                    rand.shuffle(idx)
                    Num_Values=Num_Values[idx]
                    Num_Tokens=Num_Tokens[idx]
                    a=int(sum(Num_Values[:3]))
                b=int(sum(Num_Values[3:6]))
            c=int(sum(Num_Values[6:10]))
        d=int(sum(Num_Values[10:14]))
    
    Res=[np.array([Nam[0],Num_Tokens[0]])]
    for i in np.arange(1,18):
        if i <=2:
            Res.append(np.array([Nam[0],Num_Tokens[i]]))
        elif 2 < i and i <= 5:
            Res.append(np.array([Nam[1],Num_Tokens[i]]))
        elif 5 < i and i <= 9:
            Res.append(np.array([Nam[2],Num_Tokens[i]]))
        elif 9 < i and i <= 13:
            Res.append(np.array([Nam[3],Num_Tokens[i]]))
        else:
            Res.append(np.array([Nam[4],Num_Tokens[i]]))
    Res.append(np.array(['Desert',0]))
    Num_Values=np.append(Num_Values,0)
    return(Res,Num_Values)
        

In [458]:
def pickn(box=None,idx=None,result=None): #list, array, list
    n=0
    change=box
    for k in idx:
        result.append(k)
        
    for i in np.sort(idx):
        change=np.append(change[:i-n],change[i+1-n:])
        n=n+1
        
    return(box,list(change),result) #list, list, list

def pick1(box=None,idx=None,result=None): #list, array, list
    change=box
    result.append(idx)
    change=np.append(change[:i],change[i+1:])
        
    return(box,list(change),result) #list, list, list

def setupboard(hexes=None):
    Token=list(hexes[1])
    
    sumrange=[9,10,11]
    for a in np.arange(len(Token)): #looping over all hex as starting hex
        order=[]
        available1=pick1(available,a,order)[1]
        order=pick1(available1,a,order)[2]
        seeds=rand.randint(0,len(available1)-1)
        if order[0]+available1[seeds] >= 5:
            available1=pick1(available,seeds,order)[1]
            order=pick1(available1,seeds,order)[2]
            for i in np.arange(5):
                seeds=rand.randint(0,len(available1)-1)
                while available[order[0]] + available[order[1+i]] not in sumrange:
                    seeds=rand.randint(0,len(available1)-1)
                available1=pick1(available1,seeds,order)[1]
                order=pick1(available1,seeds,order)[2]
        break
    return(order)
            


        
        

In [456]:
test=Num2Res(2)
print(test)

([array(['Brick', '9'],
      dtype='<U5'), array(['Brick', '10'],
      dtype='<U5'), array(['Brick', '5'],
      dtype='<U5'), array(['Ore', '9'],
      dtype='<U3'), array(['Ore', '6'],
      dtype='<U3'), array(['Ore', '11'],
      dtype='<U3'), array(['Lumber', '8'],
      dtype='<U6'), array(['Lumber', '3'],
      dtype='<U6'), array(['Lumber', '4'],
      dtype='<U6'), array(['Lumber', '5'],
      dtype='<U6'), array(['Grain', '2'],
      dtype='<U5'), array(['Grain', '3'],
      dtype='<U5'), array(['Grain', '4'],
      dtype='<U5'), array(['Grain', '6'],
      dtype='<U5'), array(['Sheep', '8'],
      dtype='<U5'), array(['Sheep', '12'],
      dtype='<U5'), array(['Sheep', '10'],
      dtype='<U5'), array(['Sheep', '11'],
      dtype='<U5'), array(['Desert', '0'],
      dtype='<U6')], array([4, 3, 4, 4, 5, 2, 5, 2, 3, 4, 1, 2, 3, 5, 5, 1, 3, 2, 0]))


In [268]:
a=[[0,1,-1],[-1,1,0],[-1,0,1],[0,-1,1],[1,-1,0],[1,0,-1]]
a.append([[0,0,0],[1,2,3]])
print(a)

[[0, 1, -1], [-1, 1, 0], [-1, 0, 1], [0, -1, 1], [1, -1, 0], [1, 0, -1], [[0, 0, 0], [1, 2, 3]]]


In [459]:
a=np.array([2,3,5,6,7,8,8,9,5,1,1,2])
pick1(a,2,[])

(array([2, 3, 5, 6, 7, 8, 8, 9, 5, 1, 1, 2]),
 [2, 3, 5, 6, 7, 8, 8, 9, 5, 1, 1, 2],
 [2])

In [449]:
2*3 not in [1,2,3,4,5,6]

False

In [273]:
def spiral(center=None,radius=None):
    cubedirect=np.vstack([np.array([1,-1,0]),np.array([1,0,-1]),np.array([0,1,-1]),np.array([-1,1,0]),np.array([-1,0,1]),np.array([0,-1,1])])       

    result=[np.array(center)]
    
    for k in np.arange(1,radius+1):
        cube=np.array(center)+cubedirect[-2]*k
        result.append(cube)
        for i in np.arange(6):
            for j in np.arange(k):
                cube = cube + cubedirect[i]
                result.append(cube)
        result=result[:-1]

    return result
